export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const FORGOT_PASSWORD = '/forgot-password'
export const TAG = '/tag'
export const HOME = '/'
export const WALL = '/wall'
export const PROFILE = '/profile'
export const EDIT_PROFILE = '/edit-profile'
